In [1]:
%matplotlib inline
import ncstudy.analysis as analysis
import numpy as np
import pdb
import time
import matplotlib.pyplot as plt
import matplotlib
# plt.style.use('dark_background')

# Full analysis run for viewing results only

In [ ]:
A = analysis.Analysis('../../data')
A.run(fig_dir='../../figures/manuscript', redo_modality=True, redo_MI=True);
# A = analysis.Analysis('./data')
# A.run(fig_dir='./figures/manuscript');

Loading...


 33%|███▎      | 1/3 [00:01<00:02,  1.47s/it]

HERE


 67%|██████▋   | 2/3 [00:02<00:01,  1.48s/it]

HERE


100%|██████████| 3/3 [00:04<00:00,  1.48s/it]


HERE
Updating...


  0%|          | 0/3 [00:00<?, ?it/s]/gpfs/bbp.cscs.ch/home/isbister/PrincePy3Env/lib/python3.8/site-packages/sklearn/mixture/_base.py:277: ConvergenceWarning: Initialization 30 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
  0%|          | 0/3 [00:00<?, ?it/s]

data [[-71.1059494  -67.44384003 -69.88524628 -68.96971893 -68.35936737]
 [-70.80077362 -68.35936737 -69.5800705  -70.49559784 -68.66454315]
 [-71.41112518 -68.35936737 -68.35936737 -68.96971893 -68.96971893]
 ...
 [-45.77636719 -46.99707031 -45.47119141 -45.77636719 -46.99707031]
 [-45.77636719 -46.08154297 -45.77636719 -47.60742188 -46.38671875]
 [-45.77636719 -47.91259766 -45.16601562 -47.91259766 -46.99707031]]
self.delay 1.4597170632109517
self.stim_winsize 50
self.mono_winsize 5
self.early_winsize 16.269617391728467
self.stim_winsteps 500
self.mono_winsteps 50
self.time [ 0.    0.05  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55
  0.6   0.65  0.7   0.75  0.8   0.85  0.9   0.95  1.    1.05  1.1   1.15
  1.2   1.25  1.3   1.35  1.4   1.45  1.5   1.55  1.6   1.65  1.7   1.75
  1.8   1.85  1.9   1.95  2.    2.05  2.1   2.15  2.2   2.25  2.3   2.35
  2.4   2.45  2.5   2.55  2.6   2.65  2.7   2.75  2.8   2.85  2.9   2.95
  3.    3.05  3.1   3.15  3.2   3.25  3.3   3.35  3.

 33%|███▎      | 1/3 [24:08<48:16, 1448.38s/it]

data [[-69.5800705  -69.5800705  -67.13866425 -70.80077362 -69.5800705 ]
 [-71.41112518 -70.19042206 -65.91796112 -69.5800705  -68.66454315]
 [-69.27489471 -68.66454315 -68.05419159 -70.80077362 -70.49559784]
 ...
 [-63.1713829  -60.72997665 -61.03515244 -60.11962509 -61.34032822]
 [-61.95067978 -62.56103134 -58.59374619 -61.95067978 -62.86620712]
 [-61.645504   -60.42480087 -61.34032822 -61.34032822 -62.86620712]]
self.delay 1.5784495111489187
self.stim_winsize 50
self.mono_winsize 5
self.early_winsize 10.255054702324692
self.stim_winsteps 500
self.mono_winsteps 50
self.time [ 0.    0.05  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55
  0.6   0.65  0.7   0.75  0.8   0.85  0.9   0.95  1.    1.05  1.1   1.15
  1.2   1.25  1.3   1.35  1.4   1.45  1.5   1.55  1.6   1.65  1.7   1.75
  1.8   1.85  1.9   1.95  2.    2.05  2.1   2.15  2.2   2.25  2.3   2.35
  2.4   2.45  2.5   2.55  2.6   2.65  2.7   2.75  2.8   2.85  2.9   2.95
  3.    3.05  3.1   3.15  3.2   3.25  3.3   3.35  3.

 67%|██████▋   | 2/3 [29:32<13:07, 787.23s/it] 

data [[-69.88524628 -68.96971893 -72.93700409 -70.19042206 -70.19042206]
 [-70.19042206 -71.71630096 -70.80077362 -71.41112518 -72.02147675]
 [-69.27489471 -70.49559784 -72.93700409 -68.96971893 -70.49559784]
 ...
 [-71.71630096 -71.1059494  -69.5800705  -69.88524628 -72.02147675]
 [-71.71630096 -70.49559784 -69.27489471 -70.80077362 -71.41112518]
 [-71.41112518 -69.88524628 -69.27489471 -71.41112518 -71.41112518]]
self.delay 1.5803820668091482
self.stim_winsize 50
self.mono_winsize 5
self.early_winsize 14.761231178592643
self.stim_winsteps 500
self.mono_winsteps 50
self.time [ 0.    0.05  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55
  0.6   0.65  0.7   0.75  0.8   0.85  0.9   0.95  1.    1.05  1.1   1.15
  1.2   1.25  1.3   1.35  1.4   1.45  1.5   1.55  1.6   1.65  1.7   1.75
  1.8   1.85  1.9   1.95  2.    2.05  2.1   2.15  2.2   2.25  2.3   2.35
  2.4   2.45  2.5   2.55  2.6   2.65  2.7   2.75  2.8   2.85  2.9   2.95
  3.    3.05  3.1   3.15  3.2   3.25  3.3   3.35  3.

In [ ]:
A.fig_ephys

In [ ]:
A.fig_fi

In [ ]:
A.fig_scatter

In [ ]:
A.fig_pca

In [ ]:
import matplotlib.pyplot as plt

ax = A.fig_dend.axes[0]
fluors = ['NF', 'PV+', 'SST+']
colors = ['#F5A623', '#4A90E2', '#7ED321']
for tl in ax.xaxis.get_ticklabels():
    color = [c for c,fl in zip(colors, fluors) if fl == tl.get_text()][0]
    tl.set_color(color)
    
ax.set_xlabel('Cell type', fontsize=16)
ax.set_ylabel('Distance', fontsize=16)
A.fig_dend

In [ ]:
A.fig_monorel

In [ ]:
A.fig_mean_dly

In [ ]:
A.fig_max_dly

In [ ]:
A.results['Rate']['Spikes']['mono']['fig']

In [ ]:
A.results['Rate']['Spikes']['poly']['fig']

In [ ]:
A.results['Rate']['Spikes']['all']['fig']

In [ ]:
A.results['Temporal']['Spikes']['mono']['fig']

In [ ]:
A.results['Temporal']['Spikes']['poly']['fig']

In [ ]:
A.results['Temporal']['Spikes']['all']['fig']

In [ ]:
A.results['Rate']['Average Vm']['mono']['fig']

In [ ]:
A.results['Rate']['Average Vm']['poly']['fig']

In [ ]:
A.results['Rate']['Average Vm']['all']['fig']

In [ ]:
A.results['Temporal']['Average Vm']['mono']['fig']

In [ ]:
A.results['Temporal']['Average Vm']['poly']['fig']

In [ ]:
A.results['Temporal']['Average Vm']['all']['fig']

## Clustering

In [ ]:
from pandas.plotting import scatter_matrix
import numpy as np
import matplotlib.pyplot as plt

df_ephys_transform = A.df_ephys.drop(['Adaptation Ratio', 'Vrest (mV)'], 1)
df_ephys_transform['log(Adaptation Ratio)'] = A.df_ephys['Adaptation Ratio'].apply(np.log)
axs = scatter_matrix(df_ephys_transform, alpha=0.2,figsize=(13,13), diagonal='kde')
for ax in np.ravel(axs):
    ax.set_xlabel(ax.get_xlabel().replace(' ', '\n'), fontsize=11)
    ax.set_ylabel(ax.get_ylabel().replace(' ', '\n'), fontsize=11)
    ax.spines['top'].set_visible(True)
    ax.spines['right'].set_visible(True)
    ax.yaxis.set_label_coords(-0.4, 0.5)
    ax.xaxis.set_label_coords(0.5, -0.4)

fig = plt.gcf()

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, Imputer
import pandas as pd

features = df_ephys_transform.columns.values[2:]
x = df_ephys_transform.loc[:,features].values
y = df_ephys_transform.loc[:,['Fluorescence']].values

#standardize data, used Imputer to handle NaN entries
imp = Imputer(strategy="mean", axis=0)
scale = StandardScaler()
x = scale.fit_transform(imp.fit_transform(x))
pd.DataFrame(data = x, columns = features, index=df_ephys_transform.index).head()

In [ ]:
pca = PCA(n_components=3)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents,
                           columns = ['principal component 1', 'principal component 2', 'principal component 3'],
                           index = df_ephys_transform.index)
principalDf.head(8)

In [ ]:
pca_components = pd.DataFrame(np.transpose(pca.components_), 
                columns = ['principal component 1', 'principal component 2', 'principal component 3'],
                index = features )
pca_components

In [ ]:
#concatenate PCA values to fluorescent cell
finalDf = pd.concat([principalDf, df_ephys_transform[['Fluorescence']]], axis = 1)
finalDf.head(5)

In [ ]:
import matplotlib.pyplot as plt

#1st vs 2nd component PCA plot
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 2', fontsize = 15)
ax.set_title('1st vs 2nd Principal Component', fontsize = 20)


Fluorescence = ['NF', 'PV+', 'SST+']
colors = ['#F5A623', '#4A90E2', '#7ED321']
for target, color in zip(Fluorescence,colors):
    indicesToKeep = finalDf['Fluorescence'] == target
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']
               , finalDf.loc[indicesToKeep, 'principal component 2']
               , c = color
               , s = 100)
ax.legend(Fluorescence)
ax.grid()

#1st vs 3nd component PCA plot
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 3', fontsize = 15)
ax.set_title('1st vs 3rd Principal Component', fontsize = 20)


Fluorescence = ['NF', 'PV+', 'SST+']
colors = ['#F5A623', '#4A90E2', '#7ED321']
for target, color in zip(Fluorescence,colors):
    indicesToKeep = finalDf['Fluorescence'] == target
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']
               , finalDf.loc[indicesToKeep, 'principal component 3']
               , c = color
               , s = 100)
ax.legend(Fluorescence)
ax.grid()

#2nd vs 3rd component PCA plot
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 2', fontsize = 15)
ax.set_ylabel('Principal Component 3', fontsize = 15)
ax.set_title('2nd vs 3rd Principal Components', fontsize = 20)


Fluorescence = ['NF', 'PV+', 'SST+']
colors = ['#F5A623', '#4A90E2', '#7ED321']
for target, color in zip(Fluorescence,colors):
    indicesToKeep = finalDf['Fluorescence'] == target
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 2']
               , finalDf.loc[indicesToKeep, 'principal component 3']
               , c = color
               , s = 100)
ax.legend(Fluorescence)
ax.grid()

In [ ]:
pca.explained_variance_ratio_

In [ ]:
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

#ward's linkage dendrogram
Z = linkage(x, 'ward')
plt.figure(figsize=(25, 10))
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('sample index')
plt.ylabel('distance')
dendrogram(
    Z,
    leaf_rotation=90.,  # rotates the x axis labels
    leaf_font_size=8.,  # font size for the x axis labels
    labels=y
);

# dendrogram()

# Electrophysiology analysis walkthrough

In [ ]:
import ncstudy.cell as cell
from ncstudy.utils import merge_dicts
import re
import pandas as pd
import ncstudy.plots as plots

In [ ]:
data_path = './data'
cell_ids = [os.path.basename(dirname[0])
                 for dirname in os.walk(data_path)
                 if re.match(r'\d{2}\w{1}\d{2}\-\d{1}', os.path.basename(dirname[0]))]
cell_ids.sort()
cells = cell.CellCollection(data_path= data_path)

for cell_id in cell_ids:
    celldir = '%s/%s'%(data_path, cell_id)
    neuron = cell.Cell(celldir)
    results = neuron.extract_ephys(pulse_on = 266, pulse_len = 500, sampling_frequency = 10.,
                                   I_min = -0.08, I_max = 0.4, I_step = 0.04)
    cells.add(neuron)

In [ ]:
cells['18131-2'].ephys.plot()

## Table of electrophysiological properties and descriptive statistics

In [ ]:
cells.collect_results()

In [ ]:
df = pd.DataFrame(data=merge_dicts(cells.metadata,cells.ephys), index=cells.keys());

# Reorder columns

cols = ['Fluorescence','Layer',                                                # Cell Type
        'Vrest (mV)','Input Resistance (megaohm)',                             # Passive Properties
        'Cell Capacitance (pF)','Membrane Time Constant (ms)',                 # Passive Properties
        'Rheobase (nA)','fI slope (Hz/nA)',                                    # Active Properties
        'Adaptation Ratio','Sag Amplitude (mV)',                               # Slow Properties
        'Spike Threshold (mV)','Spike Amplitude (mV)','Spike Halfwidth (ms)']  # Action Potential Properties

df = df[cols]
cells.df_ephys = df[df['Layer']=='L2/3']
cells.df_ephys.groupby('Fluorescence').mean().round(2)

In [ ]:
fig = plots.plot_ephys_summary(cells.df_ephys)
# fig.savefig('./figures/manuscript/ephys_features.svg')

In [ ]:
fig = plots.plot_fICurves(cells)

# Optogenetic Presynaptic Stimulation Walkthrough

In [ ]:
import ncstudy.cell as cell
import ncstudy.synapses as syns

In [ ]:
for cell_id, celln in cells.items():
    celln.syns = cell.Synapses(celln.celldir, mono_winsize=5, total_winsize=200, sampling_frequency=10)
    celln.syns.extract_features()

In [ ]:
cells['18202-3'].syns.plot(savefig=False, figsize=(16,6))

In [ ]:
cells.collect_results()
df = pd.DataFrame(data=merge_dicts(cells.metadata, cells.syns), index=cells.keys())
df_syns     = df[df['Layer']=='L2/3']

In [ ]:
fig = plots.plot_syn_reliability(df_syns)

##  Rate and temporal code analysis

In [ ]:
import ncstudy.cell as cell
import os
import re

data_path = './data'
cell_ids = [os.path.basename(dirname[0])
            for dirname in os.walk(data_path)
            if re.match(r'\d{2}\w{1}\d{2}\-\d{1}', os.path.basename(dirname[0]))]
cell_ids.sort()
cells = cell.CellCollection(data_path= data_path)

for cell_id in cell_ids:
    celldir = '%s/%s'%(data_path, cell_id)
    neuron = cell.Cell(celldir)


    neuron.rate_code = cell.Code(celldir=celldir, code_type='rate',
                                 stim_winsize=50, mono_winsize=5,
                                 start=5, dur=50, sampling_frequency=10)
    neuron.rate_code.estimate_mutual_information()
    
    neuron.temp_code = cell.Code(celldir=celldir, code_type='temp',
                                 stim_winsize=50, mono_winsize=5,
                                 start=5, dur=50, sampling_frequency=10)
    neuron.temp_code.estimate_mutual_information()
    
    cells.add(neuron)

In [ ]:
cells.collect_metadata()
cells.collect_syns()
cells.collect_MI()

In [ ]:
from ncstudy.utils import merge_dicts
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from itertools import combinations

df_rate_spikes = pd.DataFrame(merge_dicts(cells.metadata, cells.MI['Rate']['Spikes']), index=cells.keys())
df_rate_spikes = df_rate_spikes[df_rate_spikes['Layer']=='L2/3']
df_rate_spikes = df_rate_spikes.dropna()[['Fluorescence', 'mono', 'poly', 'all']]
df_rate_spikes.head(10)

fluor_group_keys = ['NF', 'PV+', 'SST+']
fluor_group_pairs = list(combinations(range(len(fluor_group_keys)), 2))

colors = ['#F5A623', '#4A90E2', '#7ED321']
width = 0.8
alpha = 0.6
spread = 0.1

codes = ['Rate', 'Temporal']
resps = ['Spikes', 'Average Vm']
wins  = ['mono', 'poly', 'all']

figs = []
for resp in resps:
    for code in codes:
        for win in wins:
            df = pd.DataFrame(cells.metadata, index=cells.keys())
            df['MI'] = cells.MI[code][resp][win]
            df       = df[df['Layer']=='L2/3']
            df       = df.dropna()[['Fluorescence', 'MI']]
            
            fig = plt.figure(figsize=(3,4))
            plt.bar(x = np.arange(len(fluor_group_keys)),
                    height = df.groupby('Fluorescence').mean().squeeze(),
                    #yerr = df.groupby('Fluorescence').std().squeeze(),
                    width = width,
                    alpha=alpha,
                    color=colors)
            
            plt.xticks(range(len(fluor_group_keys)), fluor_group_keys)
            
            for fx, fl in enumerate(fluor_group_keys):
                vals = df[df['Fluorescence'] == fl]['MI']
                locs = np.random.randn(len(vals))*spread + fx
                plt.plot(locs, vals, 'o', color=colors[fx])
            plt.title('%s - %s - %s'%(code, resp, win))
            plt.xlabel('Cell Type')
            plt.ylabel('%sMutual Information (bits)'%('Conditional\n' if code == 'Rate' else ''))
            
            fig.set_size_inches((6,4))
            fig.subplots_adjust(right=0.5)
            ax_results = fig.add_axes([0.6,0.125,0.375,0.775])
            
            grouped_data = [df.groupby('Fluorescence').get_group(fl)['MI'] for fl in fluor_group_keys]
            _,p_levene = stats.levene(*grouped_data) # equal variances test

            test,test_string = (stats.f_oneway, 'One Way ANOVA') if p_levene > 0.05 else (stats.kruskal, 'Kruskal-Wallis (Levene\'s p = %.3f)'%p_levene)

            F, p_test = test(*grouped_data)

            result = 'Bonferroni-corrected\n%s\n'%test_string
            result += 'p = %.3f,\n%s\n\n'%(p_test, 'Significant at p<=%.3f'%(0.05/(len(wins)*len(codes))) if p_test<=0.05/(len(wins)*len(codes)) else 'n.s.')
            result += 'post-hoc tests (significant at p<= %.3f)'%(0.05/len(fluor_group_pairs))

            for pair in fluor_group_pairs:
                fl1 = pair[0]
                fl2 = pair[1]
                _, p_levene = stats.levene(grouped_data[fl1],grouped_data[fl2])
                test_string = 'ind. t-test' if p_levene > 0.05 else  'Welch t-test (Levene\'s p = %.3f)'%p_levene

                tstat, p_ttind = stats.ttest_ind(a = grouped_data[fl1], b = grouped_data[fl2], equal_var=p_levene>0.05)
                result += '\n%s vs. %s: %s p = %.3f'%(fluor_group_keys[fl1], fluor_group_keys[fl2], test_string, p_ttind)
                
            plt.sca(ax_results)
            plt.text(x=0.0, y=0.15, s=result, fontsize=14)
            plt.axis('off')

In [ ]:
df.groupby('Fluorescence').count()

In [ ]:
df[df['Fluorescence']== fl]['MI'].

## Bar Charts for Matt 

In [ ]:
df_cols = [('Rate', 'MIc', 'Spikes', '0-5 ms'),
          ('Rate', 'MIc', 'Spikes', '0-50 ms'),
          ('Rate', 'MIc', 'Spikes', '5-50 ms'),
          ('Temp', 'MI', 'Spikes', '0-5 ms'),
          ('Temp', 'MI', 'Spikes', '0-50 ms'),
          ('Temp', 'MI', 'Spikes', '5-50 ms')
          ]

df_grouping = [('Fluorescence',np.nan,np.nan,np.nan)]

fluor_group_keys = ['NF', 'PV+', 'SST+']
fluor_group_pairs = list(combinations(range(len(fluor_group_keys)), 2))

colors = ['#F5A623', '#4A90E2', '#7ED321']

width = 0.8
alpha = 0.6
spread = 0.1

for col in df_cols:
    
    '''Figures'''
    
    df_bars = df_MI[df_grouping + [col]]
    df_bars_grouped = df_bars.groupby(df_grouping)
    means = df_bars_grouped.mean()
    stds = df_bars_grouped.std()
    
    conds_title = ('Temporal' if 'Temp' in col else 'Rate',
                   'V$_m$' if 'avVm' in col else col[-1] + ' Spike' if 'Spikes' in col else 'Slopes')
    
    conds_save = ('Temporal' if 'Temp' in col else 'Rate',
                   'avVm' if 'avVm' in col else col[-1] + 'Spike' if 'Spikes' in col else 'Slopes')
                 
    
    fig = plt.figure(figsize=(6,4))
    plt.bar(np.arange(3), means[col], yerr= stds[col], width=width, alpha = alpha, color = colors, ecolor = colors)

    for ix,fl in enumerate(fluor_group_keys):
        vals = df_bars_grouped.get_group(fl)[col]
        spread_vals = np.ones_like(vals)*ix + np.random.randn(len(vals))*spread
        plt.plot(spread_vals, vals, '.', color=colors[ix], ms = 10, zorder = -2, alpha=0.6)
    plt.xticks(range(3),fluor_group_keys)
    plt.xlabel('Cell Type')
    plt.ylabel('%sMutual Information (bits)'%('Conditional\n' if 'MIc' in col else ''))
    title_string = '%s Code\n%s Response'%conds_title

    plt.title(title_string)
    
    '''Stats'''
    
    grouped_data = [df_bars.groupby(df_grouping).get_group(fl)[col] for fl in fluor_group_keys]
    _,p_levene = stats.levene(*grouped_data) # equal variances test
    
    test,test_string = (stats.f_oneway, 'One Way ANOVA') if p_levene > 0.05 else (stats.kruskal, 'Kruskal-Wallis (Levene\'s p = %.3f)'%p_levene)
    
    F, p_test = test(*grouped_data)
    
    result = 'Bonferroni-corrected\n%s\n'%test_string
    result += 'p = %.3f,\n%s\n\n'%(p_test, 'Significant at p<=%.3f'%(0.05/len(df_cols)) if p_test<=0.05/len(df_cols) else 'n.s.')
    result += 'post-hoc tests (significant at p<= %.3f)'%(0.05/len(fluor_group_pairs) )
    
    for pair in fluor_group_pairs:
        fl1 = pair[0]
        fl2 = pair[1]
        _, p_levene = stats.levene(grouped_data[fl1],grouped_data[fl2])
        test_string = 'ind. t-test' if p_levene > 0.05 else  'Welch t-test (Levene\'s p = %.3f)'%p_levene

        tstat, p_ttind = stats.ttest_ind(a = grouped_data[fl1], b = grouped_data[fl2], equal_var=p_levene>0.05)
        result += '\n%s vs. %s: %s p = %.3f'%(fluor_group_keys[fl1], fluor_group_keys[fl2], test_string, p_ttind)
    
    fig.subplots_adjust(right=0.5)
    ax_results = fig.add_axes([0.6,0.125,0.375,0.775])
    plt.sca(ax_results)
    plt.text(x=0.0, y=0.15, s=result, fontsize=14)
    plt.axis('off')
    
    fig.savefig('./figures/manuscript/MI_%s_%s_'%conds_save+'.svg')

In [ ]:
df_MI.loc['18d27-1']['Temp','MI', 'Spikes']

### Extreme example traces

In [ ]:
'''Extreme MI traces'''

minMI_celldirs = np.array(df_bars.groupby(df_grouping).idxmin())
maxMI_celldirs = np.array(df_bars.groupby(df_grouping).idxmax())

for ii,fl in enumerate(fluor_group_keys):
    for jj,col in enumerate(df_cols):
        min_celldir = minMI_celldirs[ii,jj]
        max_celldir = maxMI_celldirs[ii,jj]
        newdir = './figures/FENS_poster/extreme_MI/'

        fileType = col[0] if col[0] is 'Rate' else 'Temporal'
        respType = col[2]
        
        min_filename = './%s/%s_1.svg'%(min_celldir,fileType)
        min_newfilename = '%s%s_example_%s_%s_lowMI.svg'%(newdir, fl,fileType, respType)
        
        max_filename = './%s/%s_1.svg'%(max_celldir,fileType)
        max_newfilename = '%s%s_example_%s_%s_highMI.svg'%(newdir, fl,fileType, respType)
        
        os.system('cp %s %s'%(min_filename, newdir))
        os.system('mv %s%s_1.svg %s'%(newdir,fileType,min_newfilename))
        
        os.system('cp %s %s'%(max_filename, newdir))
        os.system('mv %s%s_1.svg %s'%(newdir,fileType,max_newfilename))

In [ ]:
fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True,sharey=True)
for MItype,ax,title in zip(MI_avVm,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for fluorLabel,fluorType,color in zip(['GFP-','GAD67-GFP+','GIN-GFP+'],['NF','PV+','SST+'],['C0','C1','C2']):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorType])
        plt.plot(MI_bycell.T,'-o',color=color,zorder=-2,lw=1,alpha=0.2)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.fill_between(range(6),avMI+sdMI,avMI-sdMI,alpha=0.2)
        plt.plot(range(6),avMI,'-o',ms=10,label=fluorLabel+' (n=%i)'%len(MI_bycell))
        
    plt.title(title)
    plt.xticks(range(6),sampling_freqs)
    plt.xlabel('Sampling Frequency (Hz)')

plt.legend()
plt.sca(axs[0])
plt.ylabel('Mutual Information (bits)\nI($V_m$ average; state)')

fig.savefig('./figures/svg/MI_avVm'+(time.strftime("%d-%m-%Y-%H-%M-%S"))+'.svg')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

view_win = 20

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MI_avVm,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        MI_bycell = MI_bycell[:, np.array(sampling_freqs)==view_win].squeeze()
        if '\n(n=%i)'%len(MI_bycell) not in fluorLabels[ix]:
            fluorLabels[ix] = fluorLabels[ix] +'\n(n=%i)'%len(MI_bycell)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.bar(ix,avMI,alpha=0.5)
        plt.errorbar(ix,avMI,sdMI,fmt='o',ms=10)
        plt.plot(np.ones_like(MI_bycell)*ix+np.random.randn(len(MI_bycell))*0.05,MI_bycell,
                 'o',color=colors[ix],alpha=0.5)
        
    plt.title(title)
    plt.xticks(range(3),fluorLabels)

plt.sca(axs[0])
plt.ylabel('Mutual Information (bits)\nI($V_m$ average; state)')
fig.savefig('./figures/svg/MI_avVm_bar.svg')

In [ ]:
fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True,sharey=True)
for MItype,ax,title in zip(MIc_avVm,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for fluorLabel,fluorType,color in zip(['GFP-','GAD67-GFP+','GIN-GFP+'],['NF','PV+','SST+'],['C0','C1','C2']):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorType])
        plt.plot(MI_bycell.T,'-o',color=color,zorder=-2,lw=1,alpha=0.2)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.fill_between(range(6),avMI+sdMI,avMI-sdMI,alpha=0.2)
        plt.plot(range(6),avMI,'-o',ms=10,label=fluorLabel+' (n=%i)'%len(MI_bycell))
        
    plt.title(title)
    plt.xticks(range(6),sampling_freqs)
    plt.xlabel('Sampling Frequency (Hz)')

plt.legend()
plt.sca(axs[0])
plt.ylabel('Conditional\nMutual Information (bits)\nI($V_m$ average; state| pattern)')

fig.savefig('./figures/svg/MIc_avVm')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

view_win = 20

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MIc_avVm,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        MI_bycell = MI_bycell[:, np.array(sampling_freqs)==view_win].squeeze()
        if '\n(n=%i)'%len(MI_bycell) not in fluorLabels[ix]:
            fluorLabels[ix] = fluorLabels[ix] +'\n(n=%i)'%len(MI_bycell)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.bar(ix,avMI,alpha=0.5)
        plt.errorbar(ix,avMI,sdMI,fmt='o',ms=10)
        plt.plot(np.ones_like(MI_bycell)*ix+np.random.randn(len(MI_bycell))*0.05,MI_bycell,
                 'o',color=colors[ix],alpha=0.5)
        
    plt.title(title)
    plt.xticks(range(3),fluorLabels)

plt.sca(axs[0])
plt.ylabel('Conditional\nMutual Information (bits)\nI($V_m$ average; state| pattern)')
fig.savefig('./figures/svg/MIc_avVm_bar.svg')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MI_slope,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        if '\n(n=%i)'%len(MI_bycell) not in fluorLabels[ix]:
            fluorLabels[ix] = fluorLabels[ix] +'\n(n=%i)'%len(MI_bycell)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.bar(ix,avMI,alpha=0.5)
        plt.errorbar(ix,avMI,sdMI,fmt='o',ms=10)
        plt.plot(np.ones_like(MI_bycell)*ix+np.random.randn(len(MI_bycell))*0.05,MI_bycell,
                 'o',color=colors[ix],alpha=0.5)
        
    plt.title(title)
    plt.xticks(range(3),fluorLabels)

plt.sca(axs[0])
plt.ylabel('Mutual Information (bits)\nI($V_m$ slope; state)')
fig.savefig('./figures/svg/MI_slopes.svg')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MIc_slope,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        if '\n(n=%i)'%len(MI_bycell) not in fluorLabels[ix]:
            fluorLabels[ix] = fluorLabels[ix] +'\n(n=%i)'%len(MI_bycell)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.bar(ix,avMI,alpha=0.5)
        plt.errorbar(ix,avMI,sdMI,fmt='o',ms=10)
        plt.plot(np.ones_like(MI_bycell)*ix+np.random.randn(len(MI_bycell))*0.05,MI_bycell,
                 'o',color=colors[ix],alpha=0.5)
        
    plt.title(title)
    plt.xticks(range(3),fluorLabels)

plt.sca(axs[0])
plt.ylabel('Conditional\nMutual Information (bits)\nI($V_m$ slope; state| pattern)')
fig.savefig('./figures/svg/MIc_slopes.svg')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

sptw = [int(win*1000) for win in spTimeWins]

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MI_spike,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        avMI = np.nanmean(MI_bycell,axis=0)
        sdMI = np.nanstd(MI_bycell,axis=0,ddof=1)
        plt.plot(range(len(spTimeWins)),avMI,'-o',ms=10,label=fluorLabels[ix]+' (n=%i)'%len(MI_bycell))
        plt.fill_between(range(len(spTimeWins)),avMI+sdMI,avMI-sdMI,alpha=0.2,zorder=-2)
        plt.plot(range(len(spTimeWins)),MI_bycell.T,'-o',color=colors[ix],alpha=0.2,lw=1,zorder=-1)
    plt.title(title)
    plt.xlabel('Spike Window (ms)')
        
plt.xticks(range(len(sptw)),sptw)
plt.legend()

plt.sca(axs[0])
plt.ylabel('Mutual Information (bits)\nI(spikes; state)')

fig.savefig('./figures/svg/MI_spikes'+(time.strftime("%d-%m-%Y-%H-%M-%S"))+'.svg')

In [ ]:
from ncstudy.utils import hcf

In [ ]:
hcf(20, 8)

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

view_win = 0.05

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MI_spike,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        MI_bycell = MI_bycell[:, np.array(spTimeWins)==view_win].squeeze()
        if '\n(n=%i)'%len(MI_bycell) not in fluorLabels[ix]:
            fluorLabels[ix] = fluorLabels[ix] +'\n(n=%i)'%len(MI_bycell)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.bar(ix,avMI,alpha=0.5)
        plt.errorbar(ix,avMI,sdMI,fmt='o',ms=10)
        plt.plot(np.ones_like(MI_bycell)*ix+np.random.randn(len(MI_bycell))*0.05,MI_bycell,
                 'o',color=colors[ix],alpha=0.5)
        
    plt.title(title)
    plt.xticks(range(3),fluorLabels)

plt.sca(axs[0])
plt.ylabel('Mutual Information (bits)\nI(spikes; state)')
fig.savefig('./figures/svg/MI_spikes_bar.svg')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

sptw = [int(win*1000) for win in spTimeWins]

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MIc_spike,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        avMI = np.nanmean(MI_bycell,axis=0)
        sdMI = np.nanstd(MI_bycell,axis=0,ddof=1)
        plt.plot(range(len(spTimeWins)),avMI,'-o',ms=10,label=fluorLabels[ix]+' (n=%i)'%len(MI_bycell))
        plt.fill_between(range(len(spTimeWins)),avMI+sdMI,avMI-sdMI,alpha=0.2,zorder=-2)
        plt.plot(range(len(spTimeWins)),MI_bycell.T,'-o',color=colors[ix],alpha=0.2,lw=1,zorder=-1)
    plt.title(title)
    plt.xlabel('Spike Window (ms)')
        
plt.xticks(range(len(sptw)),sptw)
plt.legend()

plt.sca(axs[0])
plt.ylabel('Conditional\nMutual Information (bits)\nI(spikes; state| pattern)')

fig.savefig('./figures/svg/MIc_spikes'+(time.strftime("%d-%m-%Y-%H-%M-%S"))+'.svg')

In [ ]:
fluorLabels = ['GFP-','GAD67-GFP+','GIN-GFP+']
fluorTypes = ['NF','PV+','SST+']
colors = ['C0','C1','C2']

view_win = 0.05

fig,axs = plt.subplots(ncols=2,nrows=1,figsize=(12,5),sharex=True)
for MItype,ax,title in zip(MIc_spike,axs,['Rate Code','Temporal Code']):
    plt.sca(ax)
    for ix in range(3):
        MI_bycell = np.array([mi for mi,fl in zip(MItype,fluors) if fl==fluorTypes[ix]])
        MI_bycell = MI_bycell[:, np.array(spTimeWins)==view_win].squeeze()
        if '\n(n=%i)'%len(MI_bycell) not in fluorLabels[ix]:
            fluorLabels[ix] = fluorLabels[ix] +'\n(n=%i)'%len(MI_bycell)
        avMI = MI_bycell.mean(axis=0)
        sdMI = MI_bycell.std(axis=0,ddof=1)
        plt.bar(ix,avMI,alpha=0.5)
        plt.errorbar(ix,avMI,sdMI,fmt='o',ms=10)
        plt.plot(np.ones_like(MI_bycell)*ix+np.random.randn(len(MI_bycell))*0.05,MI_bycell,
                 'o',color=colors[ix],alpha=0.5)
        
    plt.title(title)
    plt.xticks(range(3),fluorLabels)

plt.sca(axs[0])
plt.ylabel('Conditional\nMutual Information (bits)\nI($V_m$ spikes; state| pattern)')
fig.savefig('./figures/svg/MIc_spikes_bar.svg')

In [ ]:
def plot_fullJointProb(pxyz,fileType,celldir,win):

    fig,axs = plt.subplots(ncols=2,figsize=(9,10),sharex=True,sharey=True)
    
    pxy0,pxy1 = pxyz

    srtp = np.ravel(pxyz)
    srtp = np.sort(srtp)
    vmax = (srtp[-3]+0.05).round(2)

    plt.sca(axs[0])
    plt.imshow(pxy0,vmin=0,vmax=vmax)
    plt.title('Low')
    plt.ylabel('Input Spike Count (Pattern)')
    plt.xlabel('Output Spike Count (Response)')

    plt.sca(axs[1])
    plt.title('High')
    plt.xlabel('Output Spike Count (Response)')
    im = plt.imshow(pxy1,vmin=0,vmax=vmax)

    plt.xlim((-0.5,5.5))
    plt.ylim((-0.5,10.5))
    plt.xticks(range(6))

    fig.text(x=0.5,y=0.975,s='%s Code (State)'%fileType,fontsize=20,horizontalalignment='center')

    fig.subplots_adjust(bottom=0.3)
    cax = fig.add_axes([0.125,0.1,0.775,0.05])

    fig.colorbar(mappable=im,cax=cax,orientation='horizontal',extend='max')
    cax.set_xlabel('P (state, pattern, response)')
    
    fig.savefig('%s/%s_joint_spikes_%i'%(celldir,fileType,int(win*1000)))
    plt.close()

In [ ]:
plot_fullJointProb(prsc,fileType=fileType)

## 4. Power Spectrum

In [ ]:
sampling_frequency = 10000

celldirs = [x[0][2:] for x in os.walk('./') if x[0].startswith('./1')]
celldirs.sort()

ff_rsq = []
rc_rsq = []
tc_rsq = []

ff_logp = []
rc_logp = []
tc_logp = []

for celldir in celldirs:
    try:
        data_ff = load_episodic('./%s/Full_field.abf'%celldir)
        data_rc = load_episodic('./%s/Rate.abf'%celldir)
        data_tc = load_episodic('./%s/Temporal.abf'%celldir)
    except IOError:
        continue

    Vm_ff = data_ff[0][6*sampling_frequency:-6*sampling_frequency,:,0]
    Vm_rc = data_rc[0][6*sampling_frequency:-6*sampling_frequency,:,0]
    Vm_tc = data_tc[0][6*sampling_frequency:-6*sampling_frequency,:,0]

    for Vm,rsq, all_logp in zip([Vm_ff, Vm_rc, Vm_tc],[ff_rsq, rc_rsq, tc_rsq], [ff_logp, rc_logp, tc_logp]):
        f,p = sig.periodogram(Vm.T,fs=sampling_frequency)
        p = p.mean(axis=0)
        logf = np.log10(f[f<200][1:])
        logp = np.log10(p[f<200][1:])
        all_logp.append(logp)
        slope, intercept, rval, pval, stderr = stats.linregress(logf, logp)
        rsq.append(rval**2)
        
Rsq = np.array([ff_rsq, rc_rsq, tc_rsq])

ff_logp = np.mean(ff_logp, axis=0)
rc_logp = np.mean(rc_logp, axis=0)
tc_logp = np.mean(tc_logp, axis=0)

In [ ]:
colors = ['mediumpurple', 'darkorange', 'dimgrey']

fig = plt.figure(figsize=(9,6))

ff_f = np.linspace(0,200,len(ff_logp)+1)[1:]
rc_f = np.linspace(0,200,len(rc_logp)+1)[1:]
tc_f = np.linspace(0,200,len(rc_logp)+1)[1:]

plt.loglog(ff_f, np.exp(ff_logp), colors[0], alpha=0.8, lw=2)
plt.loglog(rc_f, np.exp(rc_logp), colors[1], alpha=0.8, lw=2)
plt.loglog(tc_f, np.exp(tc_logp), colors[2], alpha=0.8, lw=2)

plt.legend(['Full Field', 'Rate Code', 'Temporal Code'])
plt.xlabel('Frequency')
plt.ylabel('Power')

fig.savefig('./figures/FENS_poster/power_spectrum_opto')

In [ ]:
colors = ['mediumpurple', 'darkorange', 'dimgrey']

fig = plt.figure(figsize=(6,4))
plt.bar(range(3), Rsq.mean(axis=1), yerr=Rsq.std(axis=1, ddof=1), color=colors, alpha=0.6, ecolor=colors)
for ix,group in enumerate(Rsq):
    plt.plot(np.random.randn(len(group))*0.1+ix, group, 'o',alpha=0.6,zorder=-2, color= colors[ix])

pair_combos = list(combinations(range(3),2))
results_string = 'Paired t-tests\nSignificance at p<=%.3f\n\n'%(0.05/len(pair_combos))
dataTypes = ['Full\nField', 'Rate\nCode', 'Temporal\nCode']

for pair in pair_combos:
    ix1,ix2 = pair
    _,p_test = stats.ttest_rel(Rsq[ix1],Rsq[ix2])
    results_string += '%s vs %s, p = %.3f\n'%(dataTypes[ix1][:4], dataTypes[ix2][:4], p_test)
    
plt.xticks(range(3),dataTypes)
plt.ylabel('$R^2$')
plt.title('Power Law\nPower Spectrum fit')

fig.subplots_adjust(right=0.5)
ax_results = fig.add_axes([0.6,0.125,0.375,0.775])
plt.sca(ax_results)
plt.text(x=0.0, y=0.15, s=results_string, fontsize=14)
plt.axis('off')

fig.savefig('./figures/svg/power_spectrum_rsq')